# Generated by Django 4.1 on 2022-10-31 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MultiImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_produk', models.CharField(max_length=255)),
                ('kategori_produk', models.CharField(choices=[('Makanan', 'Makanan'), ('Pakaian', 'Pakaian'), ('Perlengkapan_Rumah_Tangga', 'Perlengkapan Rumah Tangga'), ('Otomotif', 'Otomotif'), ('Alat_Tulis_Kantor', 'Alat Tulis Kantor'), ('Kesehatan', 'Kesehatan'), ('Kecantikan', 'Kecantikan'), ('Alat_Musik', 'Alat Musik'), ('Gadget', 'Gadget'), ('Aksesoris', 'Aksesoris'), ('Footwear', 'Footwear'), ('Tas', 'Tas')], default='Makanan', max_length=255)),
                ('harga_produk', models.IntegerField()),
                ('gambar_produk', models.ImageField(upload_to='images/')),
                ('deskripsi_produk', models.TextField()),
                ('link_produk', models.TextField()),
                ('is_valid', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images/')),
                ('default', models.BooleanField(default=False)),
                ('width', models.FloatField(default=100)),
                ('length', models.FloatField(default=100)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addproduct.multiimage')),
            ],
        ),
    ]
