# Generated by Django 4.1 on 2022-10-27 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_toko', models.CharField(max_length=50)),
                ('nama_produk', models.CharField(max_length=50)),
                ('kategori_produk', models.CharField(max_length=50)),
                ('harga_produk', models.IntegerField()),
                ('deskripsi_produk', models.CharField(max_length=50)),
                ('link_produk', models.CharField(max_length=50)),
            ],
        ),
    ]
