# Generated by Django 4.1 on 2022-10-27 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('addproduct', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_produk', models.CharField(max_length=50)),
                ('kategori_produk', models.CharField(max_length=50)),
                ('harga_produk', models.IntegerField()),
                ('gambar_produk', models.ImageField(upload_to='')),
                ('deskripsi_produk', models.CharField(max_length=50)),
                ('link_produk', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pemilik', models.CharField(max_length=50)),
                ('nama_project', models.CharField(max_length=50)),
                ('kategori', models.CharField(max_length=50)),
                ('bayaran', models.IntegerField()),
                ('deskripsi', models.TextField()),
                ('estimasi', models.CharField(max_length=30)),
                ('skills', models.TextField()),
                ('kontak_pemilik', models.TextField()),
                ('jumlah_orang', models.IntegerField()),
                ('acc', models.BooleanField(default=False)),
                ('buka', models.BooleanField(default=True)),
                ('id_pemilik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='MultipleImage',
        ),
        migrations.DeleteModel(
            name='product',
        ),
    ]
