# Generated by Django 4.1.1 on 2022-11-01 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addproduct', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='idToko',
            field=models.BigIntegerField(default=0),
        ),
    ]
