# Generated by Django 4.1 on 2022-10-31 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addproduct', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='gambar_produk',
        ),
    ]
