# Generated by Django 4.1 on 2022-11-01 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addproduct', '0004_alter_product_gambar_produk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gambar_produk',
            field=models.ImageField(blank=True, null=True, upload_to='addproduct/files/images/'),
        ),
    ]
