# Generated by Django 4.1 on 2022-11-01 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addproduct', '0005_alter_product_gambar_produk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='kategori_produk',
            field=models.CharField(choices=[('Makanan', 'Makanan'), ('Pakaian', 'Pakaian'), ('Perlengkapan Rumah Tangga', 'Perlengkapan Rumah Tangga'), ('Otomotif', 'Otomotif'), ('Alat Tulis Kantor', 'Alat Tulis Kantor'), ('Kesehatan', 'Kesehatan'), ('Kecantikan', 'Kecantikan'), ('Alat Musik', 'Alat Musik'), ('Gadget', 'Gadget'), ('Aksesoris', 'Aksesoris'), ('Footwear', 'Footwear'), ('Tas', 'Tas')], default='Makanan', max_length=255),
        ),
    ]
