# Generated by Django 4.1 on 2022-11-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addproduct', '0005_product_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.AlterField(
            model_name='product',
            name='deskripsi_produk',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='gambar_produk',
            field=models.TextField(max_length=255),
        ),
    ]
