# Generated by Django 4.1 on 2022-10-26 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carddisplay',
            old_name='desc',
            new_name='description',
        ),
        migrations.AddField(
            model_name='carddisplay',
            name='shop_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
