# Generated by Django 4.1 on 2022-10-27 00:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('landing', '0003_seller_remove_carddisplay_shop_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carddisplay',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
