# Generated by Django 4.1 on 2022-10-27 00:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('landing', '0004_alter_carddisplay_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='seller_name',
        ),
        migrations.AddField(
            model_name='seller',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='carddisplay',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='landing.seller'),
        ),
    ]
