# Generated by Django 4.1 on 2022-10-27 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_remove_seller_seller_name_seller_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carddisplay',
            name='image',
        ),
    ]
