# Generated by Django 4.1 on 2022-10-27 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_remove_carddisplay_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='carddisplay',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
