# Generated by Django 4.1 on 2022-10-27 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_carddisplay_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carddisplay',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='upload/'),
        ),
    ]
