# Generated by Django 4.1 on 2022-10-27 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumumkm',
            name='user',
            field=models.IntegerField(),
        ),
    ]
