# Generated by Django 4.1.1 on 2022-11-01 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('deskripsi', models.TextField(max_length=150)),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='')),
                ('file_url', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
